whitelist:
  facility_create: true
  facility_list: true
  facility_retrieve: true
  facility_update: true
  facility_partial_update: true
  organization_create: true
  organization_list: true
  organization_retrieve: true
  organization_update: true
  location_create: true
  location_list: true
  location_retrieve: true
  location_update: true
  assetlocation_create: true
  assetlocation_list: true
  assetlocation_retrieve: true
  bed_create: true
  bed_list: true
  bed_retrieve: true
  bed_update: true
  users_list: true
  users_retrieve: true
  users_getcurrentuser: true
  state_list: true
  district_list: true
  localBody_list: true
  ward_list: true
  facility_destroy: false
  organization_destroy: false
  patient_destroy: false
  consultation_destroy: false
  user_destroy: false
